name: 功能请求
description: 为这个项目提出一个想法
title: "功能："
labels: "增强"
assignees:
  - Hosiyume
body:
  - type: textarea
    id: describe-the-bug
    attributes:
      label: 您的功能请求是否与问题有关？请描述一下。
      description: 清晰简洁地描述问题是什么。例如，……时玩起来很难受
    validations:
      required: true
  - type: textarea
    id: to-Reproduce
    attributes:
      label: 描述您想要的解决方案
      description: 清晰简洁地描述你想发生什么。
  - type: textarea
    id: expected-behavior
    attributes:
      label: 描述你考虑过的替代方案
      description: 清晰简洁地描述您考虑过的任何替代解决方案或功能。
  - type: textarea
    id: additional-context
    attributes:
      label: 附加上下文
      description: 在此处添加有关功能请求的任何其他上下文或屏幕截图。
