name: 友链申请
description: 携手共进（迫真
title: "友链："
labels: "友链"
assignees:
  - Hosiyume
body:
  - type: markdown
    attributes:
      value: |
        **注意：**
        1. 玩家只能看到**在线**且**协议版本**（例如基岩版594）**相同**的友情服务器
        2. 仅限**服务器管理组**或**已获得服务器管理组授权者**进行申请，**证明材料请在附加上下文中补充**
        3. 申请前请确保**已将本服务器（源域）添加至您服务器的友链列表**，**证明材料请在附加上下文中补充**
  - type: input
    id: ip
    attributes:
      label: 地址
      placeholder: 比如[server.top]
    validations:
      required: true
  - type: input
    id: port
    attributes:
      label: 端口
      placeholder: 比如[19132]
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: 类型
      multiple: false
      options:
        - 纯生存（单世界）/生电
        - 玩法生存（多世界/模组/……）
        - 特殊生存（岛屿/大陆/……）
        - RPG
        - 小游戏
        - 群租服
        - 其他（在描述中补充）
    validations:
      required: true
  - type: textarea
    id: introduction
    attributes:
      label: 简介
      description: 对您服务器的清晰而简洁的描述。
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: 附加上下文
      description: 在此处添加有关的任何其他上下文或屏幕截图。
